print("chatbox: hello friend type 'bay' to exit")
from difflib import get_close_matches
knowledge = {
    "time": "get_time",
    "date": "get_date",
    "hi": "Hello! How can I assist you today?",
    "how are you":  "i'm good, thank you! How can I help you?",
    "what is your name": "I am arin .",
    "what can you do": "I can answer your questions and assist you with various tasks.",
    "how many days in a year": "There are 365 days in a year, except for leap years which have 366 days.",
    "what is the capital of france": "The capital of France is Paris.",
    "what is the capital of india": "The capital of India is New Delhi.",
    "what is the capital of usa": "The capital of USA is Washington, D.C",
    "what is the capital of japan": "The capital of Japan is Tokyo.",
    "what is the capital of china": "The capital of China is Beijing.",
    "what is the capital of russia": "The capital of Russia is Moscow.",
    "what is the capital of germany": "The capital of Germany is Berlin.",
    "what is the capital of italy": "The capital of Italy is Rome.",
    "what is the capital of spain": "The capital of Spain is Madrid.",
    "what is the capital of canada": "The capital of Canada is Ottawa.",
    "what is the capital of australia": "The capital of Australia is Canberra.",
    "what is the capital of brazil": "The capital of Brazil is Brasília.",
    "what is the capital of mexico": "The capital of Mexico is Mexico City.",
    "what is the capital of south africa": "The capital of South Africa is Pretoria (administrative), Bloemfontein (judicial), and Cape Town (legislative).",
    "what is the capital of argentina": "The capital of Argentina is Buenos Aires.",
    "what is the capital of egypt": "The capital of Egypt is Cairo.",
    "what is the capital of saudi arabia": "The capital of Saudi Arabia is Riyadh.",
    "what is the capital of turkey": "The capital of Turkey is Ankara.",
    "what is the capital of south korea": "The capital of South Korea is Seoul.",
    "what is the capital of indonesia": "The capital of Indonesia is Jakarta.",
    "what is the capital of nigeria": "The capital of Nigeria is Abuja.",
    "what is the capital of pakistan": "The capital of Pakistan is Islamabad.",
    "what is the capital of bangladesh": "The capital of Bangladesh is Dhaka.",
    "what is the capital of philippines": "The capital of Philippines is Manila.",
    "what is the capital of vietnam": "The capital of Vietnam is Hanoi.",
    "what is the capital of thailand": "The capital of Thailand is Bangkok.",
    "what is the capital of malaysia": "The capital of Malaysia is Kuala Lumpur.",
    "what is the capital of singapore": "The capital of Singapore is Singapore.",
    "what is the capital of new zealand": "The capital of New Zealand is Wellington.",
    "what is the capital of ireland": "The capital of Ireland is Dublin.",
    "what is the capital of portugal": "The capital of Portugal is Lisbon.",
    "what is the capital of greece": "The capital of Greece is Athens.",
    "what is the capital of sweden": "The capital of Sweden is Stockholm.",
    "what is the capital of norway": "The capital of Norway is Oslo.",                                                  
    "what is the capital of finland": "The capital of Finland is Helsinki.",
    "what is the capital of denmark": "The capital of Denmark is Copenhagen.",
    "what is the capital of poland": "The capital of Poland is Warsaw.",
    "what is the capital of czech republic": "The capital of Czech Republic is Prague.",
    "what is the capital of hungary": "The capital of Hungary is Budapest.",
    "what is the capital of austria": "The capital of Austria is Vienna.",
    "what is the capital of switzerland": "The capital of Switzerland is Bern.",
    "what is the capital of belgium": "The capital of Belgium is Brussels.",
    "what is the capital of netherlands": "The capital of Netherlands is Amsterdam.",
    "what is the capital of luxembourg": "The capital of Luxembourg is Luxembourg City.",
    "what is the capital of iceland": "The capital of Iceland is Reykjavik.",
    "what is the capital of malta": "The capital of Malta is Valletta.",
    "what is the capital of cyprus": "The capital of Cyprus is Nicosia.",
    "what is the capital of algeria": "The capital of Algeria is Algiers.",
    "what is the capital of morocco": "The capital of Morocco is Rabat.",
    "what is the capital of tunisia": "The capital of Tunisia is Tunis.",
    "what is the capital of libya": "The capital of Libya is Tripoli.",
    "what is the capital of kenya": "The capital of Kenya is Nairobi.",
    "what is the capital of uganda": "The capital of Uganda is Kampala.",
    "what is the capital of tanzania": "The capital of Tanzania is Dodoma.",
    "what is the capital of zambia": "The capital of Zambia is Lusaka.",
    "what is the capital of ghana": "The capital of Ghana is Accra.",
    "what is the capital of ivory coast": "The capital of Ivory Coast is Yamoussoukro.",
    "what is the capital of senegal": "The capital of Senegal is Dakar.",
    "what is the capital of mali": "The capital of Mali is Bamako.",
    "what is the capital of niger": "The capital of Niger is Niamey.",
    "what is the capital of chad": "The capital of Chad is N'Djamena.",
    "what is the capital of sudan": "The capital of Sudan is Khartoum.",
    "what is the capital of ethiopia": "The capital of Ethiopia is Addis Ababa.",
    "what is the capital of somalia": "The capital of Somalia is Mogadishu.",
    "what is the capital of rwanda": "The capital of Rwanda is Kigali.",
    "what is the capital of burundi": "The capital of Burundi is Gitega.",
    "what is the capital of malawi": "The capital of Malawi is Lilongwe.",
    "what is the capital of mozambique": "The capital of Mozambique is Maputo.",
    "what is the capital of angola": "The capital of Angola is Luanda.",
    "what is the capital of zimbabwe": "The capital of Zimbabwe is Harare.",
    "what is the capital of botswana": "The capital of Botswana is Gaborone.",
    "what is the capital of namibia": "The capital of Namibia is Windhoek.",
    "what is the capital of lesotho": "The capital of Lesotho is Maseru.",
    "what is the capital of swaziland": "The capital of Swaziland is Mbabane.",
    "what is the capital of comoros": "The capital of Comoros is Moroni.",
    "what is the capital of seychelles": "The capital of Seychelles is Victoria.",
    "what is the capital of mauritius": "The capital of Mauritius is Port Louis.",
    "what is the capital of cape verde": "The capital of Cape Verde is Praia.",
    "what is the capital of guinea": "The capital of Guinea is Conakry.",
    "what is the capital of sierra leone": "The capital of Sierra Leone is Freetown.",
    "what is the capital of liberia": "The capital of Liberia is Monrovia.",
    "what is the capital of central african republic": "The capital of Central African Republic is Bangui.",
    "what is the capital of cameroon": "The capital of Cameroon is Yaoundé.",
    "what is the capital of gabon": "The capital of Gabon is Libreville.",
    "what is the capital of equatorial guinea": "The capital of Equatorial Guinea is Malabo.",
    "what is the capital of sao tome and principe": "The capital of Sao Tome and Principe is Sao Tome.",
    "what is the capital of democratic republic of congo": "The capital of Democratic Republic of Congo is Kinshasa.",
    "what is the capital of republic of congo": "The capital of Republic of Congo is Brazzaville.",
    "what is the capital of burkina faso": "The capital of Burkina Faso is Ouagadougou.",
    "what is the capital of benin": "The capital of Benin is Porto-Novo.",
    "what is the capital of togo": "The capital of Togo is Lomé.",
    "what is the capital of ghana": "The capital of Ghana is Accra.",
    "what is the capital of nigeria": "The capital of Nigeria is Abuja.",
    "what is the capital of cameroon": "The capital of Cameroon is Yaoundé.",
    "what is the capital of chad": "The capital of Chad is N'Djamena.",
    "what is the capital of central african republic": "The capital of Central African Republic is Bangui.",
    "what is the capital of equatorial guinea": "The capital of Equatorial Guinea is Malabo.",
    "what is the capital of gabon": "The capital of Gabon is Libreville.",
    "what is the capital of sao tome and principe": "The capital of Sao Tome and Principe is Sao Tome.",
    "what is the capital of democratic republic of congo": "The capital of Democratic Republic of Congo is Kinshasa.",
    "what is the capital of republic of congo": "The capital of Republic of Congo is Brazzaville.",
    "what is the capital of burkina faso": "The capital of Burkina Faso is Ouagadougou.",
    "what is the capital of benin": "The capital of Benin is Porto-Novo.",
    "what is the capital of togo": "The capital of Togo is Lomé.",
    "what is the capital of mali": "The capital of Mali is Bamako.",
    "what is the capital of niger": "The capital of Niger is Niamey.",
    "what is the capital of senegal": "The capital of Senegal is Dakar.",
    "what is the capital of guinea-bissau": "The capital of Guinea-Bissau is Bissau.",
    "what is the capital of gambia": "The capital of Gambia is Banjul.",
    "what is the capital of cape verde": "The capital of Cape Verde is Praia.",
    "what is the capital of mauritania": "The capital of Mauritania is Nouakchott.",
    "what is the capital of western sahara": "The capital of Western Sahara is El Aaiún.",
    "what is the capital of morocco": "The capital of Morocco is Rabat.",
    "what is the capital of algeria": "The capital of Algeria is Algiers.",
    "what is the capital of libya": "The capital of Libya is Tripoli.",
    "what is the capital of tunisia": "The capital of Tunisia is Tunis.",
    "what is the capital of egypt": "The capital of Egypt is Cairo.",
    "what is the capital of sudan": "The capital of Sudan is Khartoum.",
    "what is the capital of south sudan": "The capital of South Sudan is Juba.",
    "what is the capital of ethiopia": "The capital of Ethiopia is Addis Ababa.",
    "what is the capital of eritrea": "The capital of Eritrea is Asmsara.",
    "what is the capital of djibouti": "The capital of Djibouti is Djibouti.",
    "what is the capital of somalia": "The capital of Somalia is Mogadishu.",
    "what is the capital of kenya": "The capital of Kenya is Nairobi.",
    "what is the capital of uganda": "The capital of Uganda is Kampala.",
    "what is the capital of tanzania": "The capital of Tanzania is Dodoma.",
    "what is the capital of rwanda": "The capital of Rwanda is Kigali.",
    "what is the capital of burundi": "The capital of Burundi is Gitega.",
    "what is the capital of malawi": "The capital of Malawi is Lilongwe.",
    "what is the capital of mozambique": "The capital of Mozambique is Maputo.",
    "what is the capital of zambia": "The capital of Zambia is Lusaka.",
    "what is the capital of angola": "The capital of Angola is Luanda.",
    "what is the capital of namibia": "The capital of Namibia is Windhoek.",
    "what is the capital of botswana": "The capital of Botswana is Gaborone.",
    "what is the capital of lesotho": "The capital of Lesotho is Maseru.",
    "what is the capital of swaziland": "The capital of Swaziland is Mbabane.",
    "what is the capital of comoros": "The capital of Comoros is Moroni.",
    "what is the capital of seychelles": "The capital of Seychelles is Victoria.",
    "what is the capital of mauritius": "The capital of Mauritius is Port Louis.",
    "what is the capital of madagascar": "The capital of Madagascar is Antananarivo.",
    "what is the capital of reunion": "The capital of Reunion is Saint-Denis.",
    "what is the capital of mayotte": "The capital of Mayotte is Mamoudzou.",
    "what is the capital of french polynesia": "The capital of French Polynesia is Papeete.",
    "what is the capital of new caledonia": "The capital of New Caledonia is Nouméa.",
    "what is the capital of wallis and futuna": "The capital of Wallis and Futuna is Mata-Utu.",
    "what is the capital of cook islands": "The capital of Cook Islands is Avarua.",
    "what is the capital of niue": "The capital of Niue is Alofi.",
    "what is the capital of american samoa": "The capital of American Samoa is Pago Pago.",
    "what is the capital of samoa": "The capital of Samoa is Apia.",    
    "what is the capital of tonga": "The capital of Tonga is Nuku'alofa.",
    "what is the capital of fiji": "The capital of Fiji is Suva.",
    "what is the capital of vanuatu": "The capital of Vanuatu is Port Vila.",
    "what is the capital of solomon islands": "The capital of Solomon Islands is Honiara.",
    "what is the capital of kiribati": "The capital of Kiribati is Tarawa.",
    "what is the capital of tuvalu": "The capital of Tuvalu is Funafuti.",
    "what is the capital of palau": "The capital of Palau is Ngerulmud.",
    "what is the capital of micronesia": "The capital of Micronesia is  Palikir.",
    "what is the capital of marshall islands": "The capital of Marshall Islands is Majuro.",
    "what is the capital of nauru": "The capital of Nauru is Yaren.",
    "what is the capital of tanzania": "The capital of Tanzania is Dodoma.",    
    "what is the capital of zambia": "The capital of Zambia is Lusaka.",
    "what is the capital of malawi": "The capital of Malawi is Lilongwe.",
    "what is the capital of mozambique": "The capital of Mozambique is Maputo.",
    "what is the capital of angola": "The capital of Angola is Luanda.",
    "what is the capital of namibia": "The capital of Namibia is Windhoek.",
    "what is the capital of botswana": "The capital of Botswana is Gaborone.",
    "what is the capital of lesotho": "The capital of Lesotho is Maseru.",
    "what is the capital of swaziland": "The capital of Swaziland is Mbabane.",
    "what is the capital of comoros": "The capital of Comoros is Moroni.",
    "what is the capital of seychelles": "The capital of Seychelles is Victoria.",
    "what is the capital of mauritius": "The capital of Mauritius is Port Louis.",
    "what is the capital of madagascar": "The capital of Madagascar is Antananarivo.",
    "what is the capital of reunion": "The capital of Reunion is Saint-Denis.", 
    "what is the capital of mayotte": "The capital of Mayotte is Mamoudzou.",
    "what is the capital of cook islands": "The capital of Cook Islands is Avarua.",
    "what is the capital of niue": "The capital of Niue is Alofi.",
    "what is the capital of american samoa": "The capital of American Samoa is Pago Pago.",
    "what is the capital of samoa": "The capital of Samoa is Apia.",
    "what is the capital of tonga": "The capital of Tonga is Nuku'alofa.",
    "what is the capital of fiji": "The capital of Fiji is Suva.",
    "what is the capital of vanuatu": "The capital of Vanuatu is Port Vila.",
    "what is the capital of solomon islands": "The capital of Solomon Islands is Honiara.",
    "what is the capital of kiribati": "The capital of Kiribati is Tarawa.",
    "what is the capital of tuvalu": "The capital of Tuvalu is Funafuti.",
    "what is the capital of french polynesia": "The capital of French Polynesia is Papeete.",
    "what is the capital of new caledonia": "The capital of New Caledonia is Nouméa.",
    "what is the capital of wallis and futuna": "The capital of Wallis and Futuna is Mata-Utu.",
    "what is the capital of palau": "The capital of Palau is Ngerulmud.",
    "what is the capital of micronesia": "The capital of Micronesia is Palikir.",
    "what is the capital of marshall islands": "The capital of Marshall Islands is Majuro.",
    "what is the capital of nauru": "The capital of Nauru is Yaren."}

     
def get_response(user_input):
    user_input = user_input.lower()
    matches = get_close_matches(user_input, knowledge.keys(), n=1, cutoff=0.5)
    if matches:
        return knowledge[matches[0]]
    if response == "get_time":
        now = datetime.datetime.now()
        return "The current time is " + now.strftime('%I:%M:%P') + "."
    elif response == "get_date":
        today = datetime.date.today()
        return "Today's date is" + today.strftime('%d-%m-%y')+"."
    else: 
        return "I'm sorry, I don't have an answer for that. Can you please rephrase your question?"
    
import datetime   
    
while True:
    user_input = input("You: ")
    if user_input =="time":
        now = datetime.datetime.now()
        print(f"chatbox: The current time is {datetime.now().strftime('%H:%M:%S')}.")
    elif user_input == "date":
        today = datetime.date.today()
        print(f"chatbox: Today's date is {datetime.now().strftime('%Y-%m-%d')}.")
    if user_input.lower() == "bay":
        print("chatbox: bye friend")
        break
    response = get_response(user_input)
    print(f"chatbox: {response}")